<a href="https://colab.research.google.com/github/Lavan1999/NLP-Tast_EnglishBookPageFingingUsingNLP/blob/main/10_STD_EnglishBook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
pip install PyPDF2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 4.8 MB/s eta 0:00:00


In [ ]:
import PyPDF2 as pdf

In [ ]:
#Google drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Google drive
#file_path = '/content/drive/My Drive/MDTM15/Raw Datasets/10th_English_EM_www.tntextbooks.in.pdf'
f=open( '/content/drive/My Drive/MDTM15/Raw Datasets/10th_English_EM_www.tntextbooks.in.pdf',"rb")
read = pdf.PdfReader(f) # read is object , which contains all the content, binary form is converted hear

In [ ]:
content = read.pages[0] #conten holds the property of the pages
data = content.extract_text()
print(data)

GOVERNMENT OF TAMIL NADU
ENGLISH
A publication under Free Textbook Programme of Government of Tamil Nadu
Department of School EducationSTANDARD TEN
Untouchability is Inhuman and a Crime
10th English_Preface.indd   1 28-11-2022   18:18:13
www.tntextbooks.in


In [ ]:
import pandas as pd

# Initialize an empty list to store extracted text
extracted_text = []

for i, page in enumerate(read.pages):
    # Extract text from the current page
    content = page.extract_text()
    # Apply cleaning to the extracted text
    content = content.replace("\n", "").replace("\t", "").replace("   ", "")
    # Append the cleaned text along with the corresponding index value to the list
    extracted_text.append({'x_feature': content, 'y_target': i})

df = pd.DataFrame(extracted_text)

print(df)


                                             x_feature  y_target
0    GOVERNMENT OF TAMIL NADUENGLISHA publication u...         0
1    Government of Tamil NaduFirst Edition  -2019Re...         1
2    PREFACEv   Each unit has a theme around which ...         2
3    Contents1Prose  His F irst Flight  02Poem* Lif...         3
4    1v  Marco Polo, Christopher Columbus, Ibn Batt...         4
..                                                 ...       ...
219  216Unit – 6Hello! I’m Santhiya. I want to writ...       219
220  217Unit – 7coming for the event and that we ha...       220
221  218His First Flight - Liam O’FlahertyThe Night...       221
222  LEARNING OUTCOMESLISTENINGStudents will be abl...       222
223  220English – Class XLis t of Authors and Revie...       223

[224 rows x 2 columns]


In [ ]:
df

x_feature  y_target
0    GOVERNMENT OF TAMIL NADUENGLISHA publication u...         0
1    Government of Tamil NaduFirst Edition  -2019Re...         1
2    PREFACEv   Each unit has a theme around which ...         2
3    Contents1Prose  His F irst Flight  02Poem* Lif...         3
4    1v  Marco Polo, Christopher Columbus, Ibn Batt...         4
..                                                 ...       ...
219  216Unit – 6Hello! I’m Santhiya. I want to writ...       219
220  217Unit – 7coming for the event and that we ha...       220
221  218His First Flight - Liam O’FlahertyThe Night...       221
222  LEARNING OUTCOMESLISTENINGStudents will be abl...       222
223  220English – Class XLis t of Authors and Revie...       223

[224 rows x 2 columns]

In [ ]:
df.x_feature[6]

'3tail at the far end of his ledge. Now, there was not a single scrap of food left. He had searched every inch, rooting among the rough, dirt-caked straw nest where he and his brothers and sister had been hatched. He even gnawed  at the dried pieces of eggshell. It was like eating a part of himself.He then trotted  back and forth from one end of the ledge to the other, his long gray legs stepping daintily, trying to find some means of reaching his parents without having to fly. But on each side of him, the ledge ended in a sheer fall of precipice , with the sea beneath. And between him and his parents, there was a deep, wide crack.Surely he could reach them without flying if he could only move northwards along the cliff face? But then, on what c.  What was the first catch of the young seagull’s older brother?d.  What did the young seagull manage to find in his search for food on the ledge?could he walk? There was no ledge, and he was not a fly. And above him, he could see nothing. The 

In [ ]:
df.x_feature.isnull().sum()

0

# **NLP-Using Sklearn**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer #this ll convert text into vector form matrix(token counts)

In [ ]:
b=CountVectorizer(ngram_range=(1,1))
train_x = b.fit_transform(df['x_feature'])
train_x.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# **Machine Learning**

In [ ]:
from sklearn.svm import SVC

In [ ]:
y = df['y_target']

In [ ]:
model=SVC().fit(train_x,y)

In [ ]:
test_x = b.transform(["hi"])
model.predict(test_x)

array([141])

In [ ]:
df.x_feature[142]

'139J. Read the comic strip and answer the following questions.1.What do you mean by cyber safety?2. How do you behave in a virtual platform?3. Can we read and access the information free of cost?4. Do you think that all the information online can be used without any permission?5. Which website do you often access? Why?e-mail Short for electronic mail, e-mail or email is information stored on a computer that is exchanged between two users over telecommunications. More plainly, e-mail is a message that may contain text, files, images, or other attachments sent through a network to a specified individual or group of individuals.Sample emailParts of an emailY our Name and Address with ZIP Code  Y our Phone NumberGreetings,I am sending this email in response to the job posting for [position] via [source of job posting]. My name is [name] and I believe I will be a good addition to your company. I graduated with a degree in [degree subject]  from  [name of school or university]  with a focus




















# **NLP-Using Spacy**

In [ ]:
pip install spacy

In [ ]:
!python -m spacy download en_core_web_sm

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 16.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
import spacy
nlp = spacy.load("en_core_web_sm")
doc = [nlp(i) for i in df['x_feature']]
doc

[GOVERNMENT OF TAMIL NADUENGLISHA publication under Free Textbook Programme of Government of Tamil NaduDepartment of School EducationSTANDARD TENUntouchability is Inhuman and a Crime10th English_Preface.indd1 28-11-202218:18:13www.tntextbooks.in,
 Government of Tamil NaduFirst Edition  -2019Revised Edition  -2020, 2022, 2023(Published under new syllabus)Tamil NaduTextbook and Educational Services Corporationwww.textbooksonline.tn.nic.inState Council of Educational Research and Training© SCERT 2019Printing & PublishingContent CreationIIThe wisepossess allNOT FOR SALE10th English_Preface.indd2 28-11-202218:18:13www.tntextbooks.in,
 PREFACEv   Each unit has a theme around which the prose selection, poem and supplementary selection has been woven.v   The four major skills, namely, listening, speaking, reading and writing have been integrated into each unit.v   Grammar rules with adequate exercises for practice have been framed to gain mastery over the language.v   Sample exercises with pro

In [ ]:
train_x_nlp = [i.vector for i in doc]
train_x_nlp

In [1]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model = RandomForestClassifier().fit(train_x_nlp,df['y_target'])

In [ ]:
test_x = ["""In this lesson, we find plural forms
such as furniture, houses, windows,
burglars, boxes, shelves, policemen. You
may notice that these words have taken
up different suffixes to form plurals. This
is because English words have different
origins.","playing rugby""","""James Grover Thurber
(1894–1961) was an
American cartoonist,
author, humourist,
journalist, playwright,
and celebrated wit. He
was best known for his cartoons and
short stories published mainly in The
New Yorker magazine, such as "The
Catbird Seat", and collected in his
numerous books."""]

In [ ]:
test_x_doc = [nlp(i) for i in test_x]
test_x_nlp = [i.vector for i in test_x_doc]
model.predict(test_x_nlp)

array([96,  4])